### ISSUE TITLE
Permission class not found for triggerdialog 

### ISSUE THREAD

**Issue by github-luckow-org** [bitmotion/mautic-deutschepost#2]
I played a little bit with the permission settings in mautic. On that this pops up. Is this a part on my side or is this a missing "feature" in triggerdialog?

`[2019-12-11 18:56:26] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: “Permission class not found for triggerdialog in permissions classes” at /app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 128 {“exception”:"[object] (InvalidArgumentException(code: 0): Permission class not found for triggerdialog in permissions classes at /app/code/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:128)"}
[2019-12-11 18:56:38] mautic.ERROR: InvalidArgumentException: Permission class not found for triggerdialog in permissions classes - in file /app/bundles/CoreBundle/Security/Permissions/CorePermissions.php - at line 128`

**Comment by ekkeguembel** [comment]
Researching.

**Comment by FlorianWessels** [comment]
Hi,

this is on our site. We will come up with a fix for that.

Thanks
Flo
